services:
  greetings-backend:
    container_name: greetings-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/code
    environment:
      - NAME="VictorHJ"
      - OTEL_LOG_LEVEL=DEBUG
      - MODE=otlp-grpc
      - OTLP_LOGS_GRPC_ENDPOINT=collector:4317
      - OTLP_TRACES_GRPC_ENDPOINT=collector:4317
      - OTLP_TRACES_HTTP_ENDPOINT=http://collector:4318/v1/traces
      - OTLP_METRICS_HTTP_ENDPOINT=http://collector:4318/v1/metrics
      - HOST_PROC=/hostfs/proc
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317
      - OTEL_SERVICE_NAME="greetings-service"


  collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    volumes:
      - ./collector/collector.yaml:/etc/otel-collector-config.yaml
      - /proc:/hostfs/proc
      - .:/code
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
