version: '3'

services:
  greetings-backend:
    container_name: greetings-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      - NAME="VictorHJ"
      - OTEL_LOG_LEVEL=ERROR

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  jaeger:
    image: jaegertracing/all-in-one:1.49
    ports:
      - "16686:16686"
      - "14250:14250"
    environment:
      - LOG_LEVEL=debug
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true

  collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./collector/collector.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "8889:8889"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
      - prometheus
