global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'greetings-backend'
    static_configs:
      - targets: ['greetings-backend:80']
  
  - job_name: prometheus

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]