apiVersion: v1
kind: Service
metadata:
  name: greetings-backend-service
spec:
  selector:
    app: greetings-backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  type: LoadBalancer